baseURL = "http://jurek333.github.io/"
languageCode = "pl-PL"
title = "[jurek333]"
theme = "jurek333-xmin"
contentDir = "..\\content"
defaultContentLanguage = "pl"
publishDir = "..\\public"
staticDir = "..\\static"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pygmentsUseClasses = true
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "dziedziny"
  tags = "zagadnienia"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Strona główna"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Dziedziny"
    url = "/dziedziny/"
    weight = 3
[[menu.main]]
    name = "Zagadnienia"
    url = "/zagadnienia/"
    weight = 4

[params]
    description = "mov [jurek333], al"
    footer = "&copy; [Jurek333](https://jurek333.github.io) 2020"