baseURL = "http://jurek333.github.io/"
languageCode = "pl-PL"
title = "[jurek333]"
theme = "retro-tech-theme"
contentDir = "../content"
defaultContentLanguage = "pl"
publishDir = "../public"
staticDir = "../static"
dataDir = "../data"
googleAnalytics = "UA-59557559-2"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pygmentsUseClasses = true
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  category = "tematy"
  tags = "znaczniki"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Główna"
    url = "/"
    pre = "📐"
    weight = 1
[[menu.main]]
    name = "Tematy"
    url = "/tematy/"
    pre = "📝"
    weight = 3
[[menu.main]]
    name = "Znaczniki"
    url = "/znaczniki/"
    pre = "🏷️"
    weight = 4

[params]
    math = true
    description = "mov [jurek333], al"
    footer = "&copy; [Jurek333](https://jurek333.github.io) 2026"
    staticman_api = "https://jurek333-comments.azurewebsites.net/v2/entry/jurek333/jurek333.github.io/source/comments"
    logo = "/img/kapibara_transparent.webp"
    logoDark = "/img/kapibara_transparent.webp"
    syntaxHighlight = true
