name: github pages

on:
    push:
        branches:
            - source

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2.4.11
              with:
                  hugo-version: '0.69.2'

            - name: config
              run: cd engine && hugo config

            - name: Build
              run: (ls ./public -R; cd engine; hugo --config ./config.toml; ls ../public -R)

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: master
                  full_commit_message: ${{ github.event.head_commit.message }}
